import { JetBrains_Mono } from 'next/font/google';
import { VT323 } from 'next/font/google';
import "./globals.css";

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
  display: 'swap',
});

const vt323 = VT323({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-vt323',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jetbrains.variable} ${vt323.variable}`}>
      <body className="font-body antialiased">
        {children}
      </body>
    </html>
  );
}
